name: FOD GitHub Action (Debug)

on:
  push:
    branches:
    - master
    - feature/**
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: papeloto/action-zip@v1
        with:
          files: src/index.js
          dest: fod.zip
      - uses: fortify-community-plugins/fod-github-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          fod_credential_type: 'api'
          fod_access_key: ${{ secrets.FOD_ACCESS_KEY }}
          fod_secret_key: ${{ secrets.FOD_SECRET_KEY }}
          bsi_token: ${{ secrets.BSI_TOKEN }}
          entitlement_preference: 'SubscriptionOnly'
          remediation_scan_preference: 'NonRemediationScanOnly'
          in_progress_scan_action: 'DoNotStartScan'
          audit_preference_id: 'Automated'
          zip_location: 'fod.zip'
          polling_interval: '1'
          notes: 'Test Scan'
          update_commit: true
          update_pr: true
