name: FOD GitHub Action (Debug)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: papeloto/action-zip@v1
        with:
          files: index.js
          dest: fod.zip
      - uses: fortify-community-plugins/fod-github-action@master
        with:
          fod_credential_type: 'api'
          fod_access_key: ${{ secrets.FOD_ACCESS_KEY }}
          fod_secret_key: ${{ secrets.FOD_SECRET_KEY }}
          bsi_token: ${{ secrets.BSI_TOKEN }}
          entitlement_preference: 'SubscriptionOnly'
          remediation_scan_preference: 'NonRemediationScanOnly'
          in_progress_scan_action: 'DoNotStartScan'
          audit_preference_id: 'Automated'
          zip_location: 'fod.zip'
          polling_interval: '5'
          notes: 'Test Scan'
