name: FOD GitHub Action Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Debug
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./github/actions/debug-action
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          fod_access_key: ${{ secrets.FOD_ACCESS_KEY }}
          fod_secret_key: ${{ secrets.FOD_SECRET_KEY }}
          bsi_token: ${{ secrets.BSI_TOKEN }}
          entitlement_preference: 'SubscriptionOnly'
          remediation_scan_preference: 'NonRemediationScanOnly'
          in_progress_scan_action: 'DoNotStartScan'
          zip_location: 'fod.zip'
          polling_interval: '5'
